//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutPic {
            get {
                object obj = ResourceManager.GetObject("AboutPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackGround_Pic {
            get {
                object obj = ResourceManager.GetObject("BackGround_Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Behzad_kh {
            get {
                object obj = ResourceManager.GetObject("Behzad_kh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clean {
            get {
                object obj = ResourceManager.GetObject("clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_off {
            get {
                object obj = ResourceManager.GetObject("database_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_on {
            get {
                object obj = ResourceManager.GetObject("database_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Email {
            get {
                object obj = ResourceManager.GetObject("Email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Moby_Dock {
            get {
                object obj = ResourceManager.GetObject("Moby_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap package_games_board {
            get {
                object obj = ResourceManager.GetObject("package_games_board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Padideh {
            get {
                object obj = ResourceManager.GetObject("Padideh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 7
        ///0 3 1
        ///0 4 2
        ///0 6 6
        ///0 8 3
        ///1 1 1
        ///1 2 4
        ///1 4 9
        ///1 8 8
        ///2 2 6
        ///2 4 3
        ///2 5 8
        ///2 8 1
        ///3 0 1
        ///3 6 8
        ///4 1 6
        ///4 3 7
        ///4 6 3
        ///4 7 1
        ///5 0 8
        ///5 1 4
        ///5 2 7
        ///5 3 5
        ///5 8 9
        ///6 0 9
        ///6 1 5
        ///6 7 8
        ///6 8 6
        ///7 1 7
        ///7 3 8
        ///7 4 5
        ///7 5 4
        ///8 0 4
        ///8 1 8
        ///8 2 2
        ///8 3 9
        ///8 4 6
        ///8 6 7
        ///8 7 3
        ///8 8 5
        ///-----
        ///0 3 5
        ///0 5 9
        ///0 7 3
        ///0 8 6
        ///1 1 9
        ///1 4 7
        ///1 5 1
        ///1 6 8
        ///2 2 3
        ///2 4 6
        ///2 7 5
        ///3 0 2
        ///3 1 5
        ///3 2 9
        ///3 3 4
        ///3 5 7
        ///3 8 8
        ///4 1 4
        ///4 2 8
        ///4 4 5
        ///4 5 6
        ///4 6 2
        ///4 7 7
        ///5 1 3
        ///5 3 1
        ///5 4 8
        ///5 5 2
        ///5 7 4
        ///5 8 9
        ///6 0 9
        ///6 1 2
        ///6 5 3
        ///6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleFile {
            get {
                return ResourceManager.GetString("SampleFile", resourceCulture);
            }
        }
    }
}
